import assert from 'node:assert/strict';
import { describe, test } from 'node:test';
import {
  checkCommit,
  findReferences,
  findToolNames,
  isAssistantBranch,
  isAssistantIdentity,
  run,
  stripSignatures,
} from './message-check.js';

const FOOTER_COMMENT = '@codex review\n\n---\n_Generated by [Claude Code](https://claude.ai/code)_';
const PERSON = { authorName: 'Tiwas', authorEmail: 'lars.m@extreme.no', committerName: 'Tiwas', committerEmail: 'lars.m@extreme.no' };

function fakeApi({ fail = false } = {}) {
  const calls = [];
  const api = async (method, path, body) => {
    calls.push({ method, path, body });
    if (fail) throw new Error('HTTP 403');
    return {};
  };
  return { api, calls };
}

describe('stripSignatures', () => {
  test('removes a footer and the rule above it', () => {
    assert.deepEqual(stripSignatures(FOOTER_COMMENT), {
      text: '@codex review',
      removed: ['_Generated by [Claude Code](https://claude.ai/code)_'],
    });
  });

  test('removes a generated-with line and a session link, keeping CRLF line ends', () => {
    const body = 'Summary\r\n\r\n🤖 Generated with [Claude Code](https://claude.com/claude-code)\r\n\r\nhttps://claude.ai/code/session_0123\r\n';
    assert.equal(stripSignatures(body).text, 'Summary');
  });

  test('removes assistant trailers and keeps human co-authors', () => {
    const message = 'fix: thing\n\nCo-authored-by: Kari <kari@example.com>\nCo-Authored-By: Claude <noreply@anthropic.com>\nClaude-Session: https://example.com/x';
    assert.equal(stripSignatures(message).text, 'fix: thing\n\nCo-authored-by: Kari <kari@example.com>');
  });

  test('removes a sign-off line', () => {
    assert.equal(stripSignatures('Fixed in abc123.\n\n— Claude').text, 'Fixed in abc123.');
  });

  test('leaves text without signatures untouched, including rules and sentences', () => {
    const text = 'Intro\n\n---\n\nThe table was generated by the export script.\n';
    assert.deepEqual(stripSignatures(text), { text, removed: [] });
  });

  test('handles empty input', () => {
    assert.deepEqual(stripSignatures(null), { text: '', removed: [] });
  });
});

describe('findToolNames', () => {
  test('finds names, links and conventions-file names', () => {
    assert.deepEqual(findToolNames('Codex review found it, see CLAUDE.md and https://chatgpt.com/x. GPT-5 too.'), [
      'Codex',
      'GPT-5',
      'https://chatgpt.com/x.',
      'CLAUDE.md',
    ]);
  });

  test('finds names in branch refs and reports a link once', () => {
    assert.deepEqual(findToolNames('Merge pull request #42 from Tiwas/codex/issue-16; see https://claude.ai/code'), [
      'codex',
      'https://claude.ai/code',
    ]);
  });

  test('ignores the review command, dot folders and other words', () => {
    assert.deepEqual(findToolNames('@codex review; `.claude/` and `.codex-logs/`; Geminimaliseerd; AI_RULES.md'), []);
  });
});

describe('findReferences', () => {
  test('finds conventions-file names and assistant links only', () => {
    assert.deepEqual(findReferences('As per CLAUDE.md and AGENTS.md, see https://claude.ai/code. @codex review'), [
      'CLAUDE.md',
      'AGENTS.md',
      'https://claude.ai/code.',
    ]);
    assert.deepEqual(findReferences('Codex found a bug'), []);
  });
});

describe('identities and branches', () => {
  test('recognises assistant identities', () => {
    assert.equal(isAssistantIdentity('Claude', 'noreply@anthropic.com'), true);
    assert.equal(isAssistantIdentity('Tiwas', 'lars.m@extreme.no'), false);
    assert.equal(isAssistantIdentity('GitHub', 'noreply@github.com'), false);
  });

  test('recognises tool-named branches', () => {
    for (const branch of ['claude/busy-hamilton-iqufvp', 'codex/issue-16-fix', 'feature/copilot-x', 'gpt']) {
      assert.equal(isAssistantBranch(branch), true, branch);
    }
    for (const branch of ['main', 'chore/remove-ai-attribution', 'fix/clg-keep-unknown-lux-sensor', 'ci/pages-actions-deploy']) {
      assert.equal(isAssistantBranch(branch), false, branch);
    }
  });
});

describe('checkCommit', () => {
  test('reports trailers, tool names and identities', () => {
    const problems = checkCommit({
      sha: 'abcdef1234',
      message: 'fix: x\n\nCo-Authored-By: Claude <noreply@anthropic.com>',
      authorName: 'Claude',
      authorEmail: 'noreply@anthropic.com',
      committerName: 'Tiwas',
      committerEmail: 'lars.m@extreme.no',
    });
    assert.equal(problems.length, 3);
    assert.match(problems[0], /^commit abcdef1: signature line/);
    assert.match(problems[2], /^commit abcdef1: author Claude/);
  });

  test('accepts a clean commit', () => {
    assert.deepEqual(checkCommit({ sha: 'abcdef1234', message: 'chore: tidy repo files', ...PERSON }), []);
  });
});

describe('run', () => {
  const repo = 'owner/repo';

  test('pull request: cleans the description and reports branch and commits', async () => {
    const { api, calls } = fakeApi();
    const ranges = [];
    const result = await run({
      eventName: 'pull_request',
      repo,
      api,
      event: {
        pull_request: {
          number: 7,
          title: 'chore: tidy',
          body: 'Changes.\n\n🤖 Generated with [Claude Code](https://claude.com/claude-code)',
          head: { ref: 'claude/x', sha: 'head' },
          base: { sha: 'base' },
        },
      },
      readCommits: (range) => {
        ranges.push(range);
        return [{ sha: 'abcdef1234', message: 'fix\n\nClaude-Session: https://claude.ai/code/s', ...PERSON }];
      },
    });
    assert.deepEqual(calls, [{ method: 'PATCH', path: '/repos/owner/repo/pulls/7', body: { body: 'Changes.' } }]);
    assert.deepEqual(ranges, [['base..head']]);
    assert.equal(result.fixes.length, 1);
    assert.deepEqual(result.problems.map((problem) => problem.split(':')[0]), [
      'branch "claude/x" is named after a tool',
      'commit abcdef1',
      'commit abcdef1',
    ]);
  });

  test('pull request: a clean PR passes without edits', async () => {
    const { api, calls } = fakeApi();
    const result = await run({
      eventName: 'pull_request',
      repo,
      api,
      event: { pull_request: { number: 8, title: 'chore: tidy', body: '', head: { ref: 'chore/tidy', sha: 'h' }, base: { sha: 'b' } } },
      readCommits: () => [{ sha: 'abcdef1234', message: 'chore: tidy', ...PERSON }],
    });
    assert.deepEqual(calls, []);
    assert.deepEqual(result, { fixes: [], problems: [] });
  });

  test('comment: removes the footer and keeps the command', async () => {
    const { api, calls } = fakeApi();
    const result = await run({
      eventName: 'issue_comment',
      repo,
      api,
      event: { comment: { id: 5, body: FOOTER_COMMENT, user: { type: 'User' } }, issue: { number: 57 } },
    });
    assert.deepEqual(calls, [{ method: 'PATCH', path: '/repos/owner/repo/issues/comments/5', body: { body: '@codex review' } }]);
    assert.deepEqual(result.problems, []);
  });

  test('comment: reports a conventions-file reference', async () => {
    const { api } = fakeApi();
    const result = await run({
      eventName: 'pull_request_review_comment',
      repo,
      api,
      event: { comment: { id: 6, body: 'Fixed, per CLAUDE.md.', user: { type: 'User' } }, pull_request: { number: 9 } },
    });
    assert.deepEqual(result.problems, ['review comment 6 on #9 names CLAUDE.md']);
  });

  test('comment: a signature-only comment is reported, not emptied', async () => {
    const { api, calls } = fakeApi();
    const result = await run({
      eventName: 'issue_comment',
      repo,
      api,
      event: { comment: { id: 7, body: '🤖 Generated with [Claude Code](https://claude.com/claude-code)', user: { type: 'User' } }, issue: { number: 1 } },
    });
    assert.deepEqual(calls, []);
    assert.deepEqual(result.problems, ['comment 7 on #1 contains only a signature; delete it']);
  });

  test('comment: bot comments are skipped', async () => {
    const { api, calls } = fakeApi();
    const result = await run({
      eventName: 'issue_comment',
      repo,
      api,
      event: { comment: { id: 8, body: 'Codex Review: see https://chatgpt.com/codex', user: { type: 'Bot' } }, issue: { number: 1 } },
    });
    assert.deepEqual(calls, []);
    assert.deepEqual(result, { fixes: [], problems: [] });
  });

  test('review: a failed edit is reported', async () => {
    const { api } = fakeApi({ fail: true });
    const result = await run({
      eventName: 'pull_request_review',
      repo,
      api,
      event: { review: { id: 9, body: FOOTER_COMMENT, user: { type: 'User' } }, pull_request: { number: 2 } },
    });
    assert.equal(result.fixes.length, 0);
    assert.match(result.problems[0], /^review 9 on #2: signature found but not removed \(HTTP 403\)$/);
  });

  test('push: picks the commit range', async () => {
    const pushes = [
      [{ ref: 'refs/heads/main', before: 'aaa', after: 'bbb' }, ['aaa..bbb']],
      [{ ref: 'refs/heads/chore/x', before: '0000000', after: 'bbb', created: true }, ['origin/main..bbb']],
      [{ ref: 'refs/heads/main', before: 'gone', after: 'bbb', forced: true }, ['-1', 'bbb']],
    ];
    for (const [push, expected] of pushes) {
      const ranges = [];
      await run({
        eventName: 'push',
        event: { ...push, repository: { default_branch: 'main' } },
        readCommits: (range) => {
          ranges.push(range);
          return [];
        },
        commitExists: (ref) => ref !== 'gone',
      });
      assert.deepEqual(ranges, [expected], push.ref);
    }
  });

  test('push: branch deletions and tags are skipped; tool-named branches are reported', async () => {
    const read = () => {
      throw new Error('must not read commits');
    };
    for (const event of [{ ref: 'refs/heads/x', deleted: true }, { ref: 'refs/tags/v1.0.0' }]) {
      assert.deepEqual(await run({ eventName: 'push', event, readCommits: read }), { fixes: [], problems: [] });
    }
    const result = await run({
      eventName: 'push',
      event: { ref: 'refs/heads/codex/fix', before: '0', after: 'b', repository: { default_branch: 'main' } },
      readCommits: () => [],
      commitExists: () => true,
    });
    assert.deepEqual(result.problems, ['branch "codex/fix" is named after a tool']);
  });
});
